package kr.hahaha98757.zombiesaddon.utils;

import java.util.Arrays;
import java.util.List;

@SuppressWarnings("SpellCheckingInspection")
public class LanguageSupport {
    public static final List<String> ZOMBIES_TITLE = Arrays.asList("ZOMBIES", "僵尸末日", "殭屍末日");
    public static final List<String> ROUND = Arrays.asList("回合", ". kolo", "Runde", "Ronde", "Kierros", "Manche", "Runde", "Γύρος", ". Kör", "Round", "ラウンド", "라운드", "Runde", "Runda", "Horda", "Rodada", "Runda", "Раунд", "Ronda", "Runda", ". Tur", "Раунд");
    public static final List<String> REVIVE = Arrays.asList("REVIVE", "等待復活", "等待救援", "OŽIVIT", "GENOPLIV", "REANIMEREN", "ELVYTÄ", "REANIMER", "WIEDERBELEBBAR", "ΑΝΑΖΩΟΓΟΝΗΣΗ", "ÉLESZTÉS", "RIANIMA", "気絶", "부활", "GJENOPPLIV", "WSKRZEŚ", "СБИТ С НОГ", "REVIVIR", "REÎNVIE", "ÅTERUPPLIVA", "YENIDEN CANLANDIR", "ЗБИТИЙ");
    public static final List<String> DEAD = Arrays.asList("DEAD", "已死亡", "已死亡", "MRTVÝ", "DØD", "DOOD", "KUOLLUT", "MORT", "TOT", "ΝΕΚΡΟΣ", "HALOTT", "MORTO", "死亡", "사망", "DØD", "ZGINĄŁ", "MORTO", "MORTO", "MORT", "МЁРТВ", "MUERTO", "DÖD", "ÖLDÜ", "МЕРТВИЙ");
    public static final List<String> QUIT = Arrays.asList("QUIT", "已退出", "已退出", "ODEJÍT", "FORLADT", "VERLATEN", "POISTU", "PARTI", "VERLASSEN", "ΕΞΟΔΟΣ", "KILÉPETT", "DISC.", "退出", "떠남", "FORLAT", "SURRENDERED", "WYJDŹ", "SAIU", "SAIU", "IEȘI", "ВЫШЕЛ", "SALIÓ", "AVSLUTA", "AYRIL", "ВИЙШОВ");
    public static final List<String> GAME_OVER = Arrays.asList("Game Over", "游戏结束", "遊戲結束", "Konec hry", "Spillet er Slut", "Spel Afgelopen", "Peli päättyi", "Partie terminée", "Das Spiel ist vorbei", "Τέλος Παιχνιδιού", "Játék Vége", "Partita Finita", "ゲームオーバー", "게임 끝", "Spillet er over", "Koniec gry", "Fim do jogo", "Fim de jogo", "Joc Încheiat", "Конец игры", "Fin Del Juego", "Spelet är över", "Oyun Bitti", "Кінець гри");
    public static final List<String> WIN = Arrays.asList("You Win", "你赢了", "你贏了", "Vyhrál jsi", "Du Vandt", "Je hebt gewonnen", "Sinä voitit", "Vous avez gagné", "Du gewinnst", "Νίκησες", "Nyertél", "Hai Vinto", "勝利", "승리했습니다", "Du vant", "Wygrywasz", "Venceste", "Vitória", "Ai Câștigat", "Вы выиграли", "Ganaste", "Du vann", "Kazandın", "Ви Перемогли");
    public static final List<String> INSTA_KILL_ENTITY = Arrays.asList("INSTA KILL", "瞬间击杀", "一擊必殺", "OKAMŽITÉ ZABITÍ", "ØJEBLIKKELIGT DRAB", "ONMIDDELLIJKE DOOD", "VÄLITÖN TAPPO", "KILL INSTANTANE", "SOFORTIGER KILL", "ΣΤΙΓΜΙΑΙΑ ΕΞΟΝΤΩΣΗ", "AZONNALI ÖLÉS", "UCCISIONE ISTANTANEA", "インスタキル", "즉시 처치", "UMIDDELBART DRAP", "NATYCHMIASTOWE ZABÓJSTWO", "KILL IMEDIATA", "ABATE INSTANTÂNEO", "INSTA-CIDERE", "МОМЕНТ. УБИЙСТВО", "MUERTE INSTANTÁNEA", "DIREKT KILL", "ANİ ÖLDÜRME", "MITTЄВE ВБИВСТВО");
    public static final List<String> INSTA_KILL_CHAT = Arrays.asList("Insta Kill", "瞬间击杀", "一擊必殺", "Zabití na ránu", "Øjeblikkeligt Drab", "Onmiddellijk Dood", "Välitön tappo", "Elimination instantanée", "Sofortiger Kill", "Στιγμιαία Εξόντωση", "Azonnali Ölés", "Uccisione Istantanea", "インスタキル", "즉시 처치", "Umiddelbart drap", "Natychmiastowe zabójstwa", "Morte instantânea", "Abate instantâneo", "Insta-Mori", "Мгновенное убийство", "Muerte Instantánea", "Direkt dödande", "Aniden Ölüm", "Миттєве вбивство");
    public static final List<String> MAX_AMMO_ENTITY = Arrays.asList("MAX AMMO", "弹药满载", "填滿彈藥", "MAXIMÁLNÍ MUNICE", "MAKS AMMUNITION", "MAXIMALE MUNITIE", "TÄYSI LIPAS", "MUNITIONS MAX", "MAXIMALE MUNITION", "ΜΕΓΙΣΤΑ ΠΥΡΟΜΑΧΙΚΑ", "MAX LŐSZER", "MUNIZIONI AL MASSIMO", "マックスアモ", "탄약 충전", "MAKS. AMMUNISJON", "Maksymalna ilość amunicji", "MUNIÇÃO MÁXIMA", "MUNIÇÃO MÁXIMA", "MUNIȚIE MAXIMĂ", "МАКС. БОЕПРИПАСОВ", "MUNICION MAXIMA", "MAX. AMMONUTION", "MAKSİMUM CEPHANE", "МАКС. НАБОЇВ");
    public static final List<String> MAX_AMMO_CHAT = Arrays.asList("Max Ammo", "弹药满载", "填滿彈藥", "Maximální munice", "Fuld Ammunition", "Max Ammunitie", "Täysi lipas", "Munitions Max", "Maximale Munition", "Γεμάτα Πυρομαχικά", "Max Lőszer", "Munizioni al Massimo", "マックスアモ", "탄약 보급", "Maks. ammunisjon", "Maksymalna Amunicja", "Munição máxima", "Munição máxima", "Muniție Maximă", "Макс. боеприпасы", "Munición Máxima", "Max ammu", "Maksimum Mermi", "Максимум набоїв");
    public static final List<String> SHOPPING_SPREE_ENTITY = Arrays.asList("SHOPPING SPREE", "购物狂潮", "購物狂潮", "NÁKUPNÍ HOREČKA", "SHOPPINGTUR", "SHOPPING SPREE", "OSTOSVILLITYS", "VIREE SHOPPING", "KAUFRAUSCH", "ΞΕΦΑΝΤΩΜΑ ΑΓΟΡΩΝ", "NAGYBEVÁSÁRLÁS", "SHOPPING SFRENATO", "ショッピングスプリー", "지름신 강림", "SHOPPING SPREE", "ZAKUPOWY SZAŁ", "FRENESIM DE COMPRAS", "MARATONA DE COMPRAS", "CUMPĂRĂTURI", "ШОППИНГ", "RACHA DE COMPRA", "SHOPPINGRUNDA", "ALIŞVERİŞ ALEMİ", "ШОППІНГ");
    public static final List<String> SHOPPING_SPREE_CHAT = Arrays.asList("Shopping Spree", "购物狂潮", "購物狂潮", "Nákupní horečka", "Shoppingtur", "Shopping Spree", "Ostosvillitys", "Frénésie d'Achats", "Einkaufsbummel", "Shopping Spree", "Nagybevásárlás", "Shopping Sfrenato", "ショッピングスプリー", "지름신 강림", "Shoppingtur", "Szał Zakupów", "Frenesim de compras", "Carrinho de compras", "Cumpărături", "Тележка", "Racha de compras", "Shoppingtur", "Alışveriş Alemi", "Візок");
    public static final List<String> DOUBLE_GOLD_ENTITY = Arrays.asList("DOUBLE GOLD", "双倍金钱", "雙倍金幣", "DVOJNÁSOBNÉ ZLATO", "DOBBELT GULD", "DUBBEL GOLD", "TUPLAKULTA", "DOUBLE OR", "DOPPELTES GOLD", "ΔΙΠΛΑΣΙΟΣ ΧΡΥΣΟΣ", "DUPLA ARANY", "ORO DOPPIO", "ダブルゴールド", "더블 골드", "DOBBELGULL", "PODWOJONE ZŁOTO", "OURO A DOBRAR", "OURO EM DOBRO", "AUR DUBLU", "УДВОЕННОЕ ЗОЛОТО", "ORO DOBLE", "DUBBELGULD", "ÇİFTE ALTIN", "ПОДВІЙНЕ ЗОЛОТО");
    public static final List<String> DOUBLE_GOLD_CHAT = Arrays.asList("Double Gold", "双倍金钱", "雙倍金幣", "Dvojnásobné zlato", "Dobbelt guld", "Dubbel Gold", "Tuplakulta", "Or Doublé", "Doppeltes Gold", "Διπλός Χρυσός", "Dupla Arany", "Oro Doppio", "ダブルゴールド", "더블 골드", "Dobbelt gull", "Podwojone Złoto", "Ouro duplo", "Ouro em dobro", "Aur Dublu", "Двойное золото", "Oro Doble", "Dubbelguld", "Çifte Altın", "Подвійне золото");
    public static final List<String> CARPENTER_ENTITY = Arrays.asList("CARPENTER", "木匠", "木匠", "TESAŘ", "TØMRER", "TIMMERMAN", "KIRVESMIES", "CHARPENTIER", "ZIMMERMANN", "ΜΑΡΑΓΚΟΣ", "ÁCS", "CARPENTIERE", "カーペンター", "카펜터", "SNEKKER", "CIEŚLA", "ARTESÃO", "CARPINTEIRO", "TÂMPLAR", "ПЛОТНИК", "CARPINTERO", "SNICKARE", "MARANGOZ", "ТЕСЛЯР");
    public static final List<String> CARPENTER_CHAT = Arrays.asList("Carpenter", "木匠", "木匠", "Tesař", "Tømrer", "Timmerman", "Kirvesmies", "Charpentier", "Zimmermann", "Μαραγκός", "Ács", "Carpentiere", "カーペンター", "목수", "Snekker", "Cieśla", "Artesão", "Carpinteiro", "Tâmplar", "Плотник", "Carpintero", "Snickare", "Marangoz", "Столяр");
    public static final List<String> BONUS_GOLD_ENTITY = Arrays.asList("BONUS GOLD", "金钱加成", "額外金幣", "BONUSOVÉ ZLATO", "BONUS GULD", "BONUS GOUD", "LISÄKULTA", "OR BONUS", "BONUS GOLD", "ΕΠΙΠΛΈΟΝ ΧΡΥΣΌΣ", "BÓNUSZ ARANY", "ORO BONUS", "ボーナスゴールド", "보너스 골드", "BONUSGULL", "DODATKOWE ZŁOTO", "OURO BÓNUS", "OURO BÔNUS", "AUR BONUS", "БОНУСНОЕ ЗОЛОТО", "BONUS DE ORO", "BONUSGULD", "BONUS ALTIN", "ДОДАТКОВЕ ЗОЛОТО");
    public static final List<String> BONUS_GOLD_CHAT = Arrays.asList("Bonus Gold", "额外金钱", "額外金幣", "Bonusové zlato", "Bonus guld", "Bonus Gold", "Lisäkulta", "Bonus d'or", "Bonus-Gold", "Bonus Χρυσός", "Bónusz Arany", "Oro Bonus", "ボーナスゴールド", "보너스 골드", "Bonusgull", "Dodatkowe złoto", "Ouro bónus", "Ouro bônus", "Aur Bonus", "Бонусное золото", "Bonif. de Oro", "Bonusguld", "Bonus Altın", "Бонусне золото");

    public static boolean isRoundText(String str) {
        for (String roundText : ROUND) if (str.contains(roundText)) return true;
        return false;
    }
}